name: Lint Markdown

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: ./.github/actions/markdown-lint
